# Generated by Django 4.2.4 on 2023-09-02 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_book_photo_alter_book_user_exchangerequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='exchange_requests',
        ),
        migrations.AddField(
            model_name='book',
            name='requested_exchanges',
            field=models.ManyToManyField(related_name='exchanges_requested_by', through='books.ExchangeRequest', to='books.book'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='book_to_exchange',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='books.book'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
